function out = model
%
% Untitled.m
%
% Model exported on Aug 23 2019, 15:44 by COMSOL 5.4.0.346.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('C:\Users\purdylab\Documents\Git_server');

model.param.set('DL', '0.00014[m]', 'Defect length');
model.param.set('DW', '1e-05[m]', 'Defect width');
model.param.set('DH', '1e-07[m]', 'Defect height');
model.param.set('Dx', '0[m]', 'Defect x position');
model.param.set('Dy', '0[m]', 'Defect y position');
model.param.set('Dz', '0[m]', 'Defect z position');
model.param.set('kx', '44879.8951[1/m]', 'Defect length');
model.param.set('MS', '7e-06[m]', 'Mesh typical size');
model.param.set('NumofUC', '5[1]', 'Unitcell number on one side');

model.component.create('mod1', false);

model.component('mod1').geom.create('geom1', 3);

model.component('mod1').mesh.create('mesh');

model.component('mod1').geom('geom1').create('wp1', 'WorkPlane');
model.component('mod1').geom('geom1').feature('wp1').geom.create('defect', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('defect').set('pos', [0 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('defect').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('defect').set('size', [1.4E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1').active(false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1').set('pos', [0 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2').active(false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2').set('pos', [0 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1').active(false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1').selection('input').set({'UCR1' 'UCR2'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1').active(false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1').selection('point').set('UCUnion1(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1').active(false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1').selection('point').set('UCCharm1(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_1', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_1').set('pos', [-7.929103558850406E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_1').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_1').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_1', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_1').set('pos', [-7.929103558850406E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_1').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_1').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_1', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_1').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_1').selection('input').set({'UCR1_1' 'UCR2_1'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_1', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_1').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_1').selection('point').set('UCUnion1_1(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_1', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_1').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_1').selection('point').set('UCCharm1_1(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_2', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_2').set('pos', [-6.322636101328094E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_2').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_2').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_2', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_2').set('pos', [-6.322636101328094E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_2').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_2').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_2', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_2').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_2').selection('input').set({'UCR1_2' 'UCR2_2'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_2', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_2').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_2').selection('point').set('UCUnion1_2(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_2', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_2').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_2').selection('point').set('UCCharm1_2(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_3', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_3').set('pos', [-4.716168643805781E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_3').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_3').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_3', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_3').set('pos', [-4.716168643805781E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_3').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_3').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_3', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_3').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_3').selection('input').set({'UCR1_3' 'UCR2_3'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_3', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_3').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_3').selection('point').set('UCUnion1_3(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_3', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_3').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_3').selection('point').set('UCCharm1_3(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_4', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_4').set('pos', [-3.109701186283469E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_4').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_4').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_4', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_4').set('pos', [-3.109701186283469E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_4').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_4').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_4', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_4').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_4').selection('input').set({'UCR1_4' 'UCR2_4'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_4', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_4').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_4').selection('point').set('UCUnion1_4(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_4', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_4').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_4').selection('point').set('UCCharm1_4(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_5', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_5').set('pos', [-1.5032337287611562E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_5').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_5').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_5', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_5').set('pos', [-1.5032337287611562E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_5').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_5').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_5', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_5').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_5').selection('input').set({'UCR1_5' 'UCR2_5'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_5', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_5').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_5').selection('point').set('UCUnion1_5(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_5', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_5').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_5').selection('point').set('UCCharm1_5(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_6', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_6').set('pos', [1.5032337287611562E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_6').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_6').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_6', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_6').set('pos', [1.5032337287611562E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_6').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_6').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_6', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_6').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_6').selection('input').set({'UCR1_6' 'UCR2_6'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_6', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_6').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_6').selection('point').set('UCUnion1_6(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_6', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_6').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_6').selection('point').set('UCCharm1_6(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_7', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_7').set('pos', [3.109701186283469E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_7').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_7').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_7', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_7').set('pos', [3.109701186283469E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_7').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_7').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_7', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_7').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_7').selection('input').set({'UCR1_7' 'UCR2_7'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_7', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_7').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_7').selection('point').set('UCUnion1_7(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_7', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_7').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_7').selection('point').set('UCCharm1_7(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_8', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_8').set('pos', [4.716168643805781E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_8').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_8').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_8', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_8').set('pos', [4.716168643805781E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_8').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_8').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_8', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_8').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_8').selection('input').set({'UCR1_8' 'UCR2_8'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_8', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_8').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_8').selection('point').set('UCUnion1_8(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_8', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_8').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_8').selection('point').set('UCCharm1_8(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_9', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_9').set('pos', [6.322636101328094E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_9').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_9').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_9', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_9').set('pos', [6.322636101328094E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_9').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_9').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_9', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_9').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_9').selection('input').set({'UCR1_9' 'UCR2_9'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_9', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_9').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_9').selection('point').set('UCUnion1_9(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_9', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_9').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_9').selection('point').set('UCCharm1_9(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR1_10', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_10').set('pos', [7.929103558850406E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_10').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR1_10').set('size', [1.6064674575223126E-4 1.0E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCR2_10', 'Rectangle');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_10').set('pos', [7.929103558850406E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_10').set('base', 'center');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCR2_10').set('size', [1.5791691945956905E-4 1.025332254379659E-5]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCUnion1_10', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_10').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCUnion1_10').selection('input').set({'UCR1_10' 'UCR2_10'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCCharm1_10', 'Chamfer');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_10').set('dist', 1.2666127189829432E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCCharm1_10').selection('point').set('UCUnion1_10(1)', [3 6 7 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('UCFillet1_10', 'Fillet');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_10').set('radius', 2.216763134320366E-7);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('UCFillet1_10').selection('point').set('UCCharm1_10(1)', [3 4 5 6 7 8 9 10]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('ls1', 'LineSegment');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('ls1').set('specify1', 'coord');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('ls1').set('coord1', [-8.732337287611562E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('ls1').set('specify2', 'coord');
model.component('mod1').geom('geom1').feature('wp1').geom.create('ls2', 'LineSegment');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('ls2').set('specify1', 'coord');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('ls2').set('specify2', 'coord');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('ls2').set('coord2', [8.732337287611562E-4 0]);
model.component('mod1').geom('geom1').feature('wp1').geom.create('Uni_small', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('Uni_small').set('intbnd', false);
model.component('mod1').geom('geom1').feature('wp1').geom.feature('Uni_small').selection('input').set({'UCFillet1_1' 'UCFillet1_2' 'UCFillet1_3' 'UCFillet1_4' 'UCFillet1_5' 'UCFillet1_6' 'UCFillet1_7' 'UCFillet1_8' 'UCFillet1_9' 'UCFillet1_10'  ...
'defect'});
model.component('mod1').geom('geom1').feature('wp1').geom.create('Uni', 'Union');
model.component('mod1').geom('geom1').feature('wp1').geom.feature('Uni').selection('input').set({'Uni_small' 'ls1' 'ls2'});
model.component('mod1').geom('geom1').create('ext1', 'Extrude');
model.component('mod1').geom('geom1').feature('ext1').set('distance', 'DH');
model.component('mod1').geom('geom1').feature('ext1').selection('input').set({'wp1.Uni'});
model.component('mod1').geom('geom1').create('difblock', 'Block');
model.component('mod1').geom('geom1').feature('difblock').set('pos', [0 5.0E-5 5.0E-8]);
model.component('mod1').geom('geom1').feature('difblock').set('base', 'center');
model.component('mod1').geom('geom1').feature('difblock').set('size', [0.0017464674575223124 1.0E-4 1.0E-7]);
model.component('mod1').geom('geom1').create('dif1', 'Difference');
model.component('mod1').geom('geom1').feature('dif1').selection('input').set({'ext1'});
model.component('mod1').geom('geom1').feature('dif1').selection('input2').set({'difblock'});
model.component('mod1').geom('geom1').run;
model.component('mod1').geom('geom1').run('fin');

model.component('mod1').material.create('Si3N4', 'Common');

model.component('mod1').physics.create('solid', 'SolidMechanics', 'geom1');
model.component('mod1').physics('solid').feature('lemm1').create('iss1', 'InitialStressandStrain', 3);
model.component('mod1').physics('solid').create('fix1', 'Fixed', 2);
model.component('mod1').physics('solid').feature('fix1').selection.set([1 97]);
model.component('mod1').physics('solid').create('sym1', 'SymmetrySolid', 2);
model.component('mod1').physics('solid').feature('sym1').selection.set([5 51]);

model.component('mod1').mesh('mesh').create('ftri', 'FreeTri');
model.component('mod1').mesh('mesh').create('swel', 'Sweep');
model.component('mod1').mesh('mesh').create('ref1', 'Refine');
model.component('mod1').mesh('mesh').create('ref2', 'Refine');
model.component('mod1').mesh('mesh').create('ref3', 'Refine');
model.component('mod1').mesh('mesh').create('ref4', 'Refine');
model.component('mod1').mesh('mesh').feature('ftri').selection.set([4]);
model.component('mod1').mesh('mesh').feature('ref1').selection.geom('geom1', 2);
model.component('mod1').mesh('mesh').feature('ref1').selection.set([4]);
model.component('mod1').mesh('mesh').feature('ref2').selection.geom('geom1', 2);
model.component('mod1').mesh('mesh').feature('ref2').selection.set([4]);
model.component('mod1').mesh('mesh').feature('ref3').selection.geom('geom1', 2);
model.component('mod1').mesh('mesh').feature('ref3').selection.set([4]);
model.component('mod1').mesh('mesh').feature('ref4').selection.geom('geom1', 2);
model.component('mod1').mesh('mesh').feature('ref4').selection.set([4]);

model.component('mod1').material('Si3N4').label('Si3N4');
model.component('mod1').material('Si3N4').propertyGroup('def').set('electricconductivity', {'0[S/m]' '0' '0' '0' '0[S/m]' '0' '0' '0' '0[S/m]'});
model.component('mod1').material('Si3N4').propertyGroup('def').set('thermalexpansioncoefficient', {'2.3e-6[1/K]' '0' '0' '0' '2.3e-6[1/K]' '0' '0' '0' '2.3e-6[1/K]'});
model.component('mod1').material('Si3N4').propertyGroup('def').set('heatcapacity', '700[J/(kg*K)]');
model.component('mod1').material('Si3N4').propertyGroup('def').set('relpermittivity', {'9.7' '0' '0' '0' '9.7' '0' '0' '0' '9.7'});
model.component('mod1').material('Si3N4').propertyGroup('def').set('density', '3100[kg/m^3]');
model.component('mod1').material('Si3N4').propertyGroup('def').set('thermalconductivity', {'20[W/(m*K)]' '0' '0' '0' '20[W/(m*K)]' '0' '0' '0' '20[W/(m*K)]'});
model.component('mod1').material('Si3N4').propertyGroup('def').set('youngsmodulus', '250e9+1e8i[Pa]');
model.component('mod1').material('Si3N4').propertyGroup('def').set('poissonsratio', '0.23');

model.component('mod1').physics('solid').feature('lemm1').feature('iss1').set('Sil', {'1e9'; '0'; '0'; '0'; '1e9'; '0'; '0'; '0'; '0'});

model.component('mod1').mesh('mesh').feature('size').set('custom', 'on');
model.component('mod1').mesh('mesh').feature('size').set('hmax', 'MS');
model.component('mod1').mesh('mesh').feature('size').set('hmin', 'MS/4');
model.component('mod1').mesh('mesh').feature('size').set('hcurve', 0.2);
model.component('mod1').mesh('mesh').feature('swel').selection('sourceface').set([4]);
model.component('mod1').mesh('mesh').feature('swel').selection('targetface').set([3]);
model.component('mod1').mesh('mesh').feature('ref1').set('rmethod', 'regular');
model.component('mod1').mesh('mesh').feature('ref1').set('boxcoord', true);
model.component('mod1').mesh('mesh').feature('ref1').set('xmax', -8.662437287611563E-4);
model.component('mod1').mesh('mesh').feature('ref1').set('xmin', -8.732437287611562E-4);
model.component('mod1').mesh('mesh').feature('ref1').set('ymax', 5.01E-6);
model.component('mod1').mesh('mesh').feature('ref1').set('ymin', -5.01E-6);
model.component('mod1').mesh('mesh').feature('ref1').set('zmax', 1.0999999999999999E-7);
model.component('mod1').mesh('mesh').feature('ref1').set('zmin', -1.0E-8);
model.component('mod1').mesh('mesh').feature('ref1').set('numrefine', 3);
model.component('mod1').mesh('mesh').feature('ref2').set('rmethod', 'regular');
model.component('mod1').mesh('mesh').feature('ref2').set('boxcoord', true);
model.component('mod1').mesh('mesh').feature('ref2').set('xmax', -8.709103954278229E-4);
model.component('mod1').mesh('mesh').feature('ref2').set('xmin', -8.732437287611562E-4);
model.component('mod1').mesh('mesh').feature('ref2').set('ymax', 5.01E-6);
model.component('mod1').mesh('mesh').feature('ref2').set('ymin', -5.01E-6);
model.component('mod1').mesh('mesh').feature('ref2').set('zmax', 1.0999999999999999E-7);
model.component('mod1').mesh('mesh').feature('ref2').set('zmin', -1.0E-8);
model.component('mod1').mesh('mesh').feature('ref3').set('rmethod', 'regular');
model.component('mod1').mesh('mesh').feature('ref3').set('boxcoord', true);
model.component('mod1').mesh('mesh').feature('ref3').set('xmax', 8.732437287611562E-4);
model.component('mod1').mesh('mesh').feature('ref3').set('xmin', 8.662437287611563E-4);
model.component('mod1').mesh('mesh').feature('ref3').set('ymax', 5.01E-6);
model.component('mod1').mesh('mesh').feature('ref3').set('ymin', -5.01E-6);
model.component('mod1').mesh('mesh').feature('ref3').set('zmax', 1.0999999999999999E-7);
model.component('mod1').mesh('mesh').feature('ref3').set('zmin', -1.0E-8);
model.component('mod1').mesh('mesh').feature('ref3').set('numrefine', 3);
model.component('mod1').mesh('mesh').feature('ref4').set('rmethod', 'regular');
model.component('mod1').mesh('mesh').feature('ref4').set('boxcoord', true);
model.component('mod1').mesh('mesh').feature('ref4').set('xmax', 8.732437287611562E-4);
model.component('mod1').mesh('mesh').feature('ref4').set('xmin', 8.709103954278229E-4);
model.component('mod1').mesh('mesh').feature('ref4').set('ymax', 5.01E-6);
model.component('mod1').mesh('mesh').feature('ref4').set('ymin', -5.01E-6);
model.component('mod1').mesh('mesh').feature('ref4').set('zmax', 1.0999999999999999E-7);
model.component('mod1').mesh('mesh').feature('ref4').set('zmin', -1.0E-8);
model.component('mod1').mesh('mesh').run;

model.study.create('std');
model.study('std').create('stat', 'Stationary');
model.study('std').create('eig', 'Eigenfrequency');
model.study('std').feature('eig').set('useadvanceddisable', true);

model.sol.create('sol1');
model.sol('sol1').study('std');
model.sol('sol1').attach('std');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').create('su1', 'StoreSolution');
model.sol('sol1').create('st2', 'StudyStep');
model.sol('sol1').create('v2', 'Variables');
model.sol('sol1').create('e1', 'Eigenvalue');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature.remove('fcDef');

model.result.evaluationGroup.create('stdEvgFrq', 'EvaluationGroup');
model.result.evaluationGroup('stdEvgFrq').set('rowstructure', []);
model.result.evaluationGroup('stdEvgFrq').create('gev1', 'EvalGlobal');
model.result.create('pg1', 'PlotGroup3D');
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').feature('surf1').create('def', 'Deform');

model.study('std').feature('stat').set('geometricNonlinearity', true);
model.study('std').feature('eig').set('neigs', 50);
model.study('std').feature('eig').set('neigsactive', true);
model.study('std').feature('eig').set('geometricNonlinearity', true);

model.sol('sol1').attach('std');
model.sol('sol1').feature('s1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('d1').label('Suggested Direct Solver (solid)');
model.sol('sol1').feature('s1').feature('i1').label('Suggested Iterative Solver (solid)');
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').set('rhob', 40);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('st2').set('studystep', 'eig');
model.sol('sol1').feature('v2').set('initmethod', 'sol');
model.sol('sol1').feature('v2').set('initsol', 'sol1');
model.sol('sol1').feature('v2').set('initsoluse', 'sol2');
model.sol('sol1').feature('v2').set('solnum', 'auto');
model.sol('sol1').feature('v2').set('notsolmethod', 'sol');
model.sol('sol1').feature('v2').set('notsol', 'sol1');
model.sol('sol1').feature('v2').set('notsolnum', 'auto');
model.sol('sol1').feature('e1').set('control', 'eig');
model.sol('sol1').feature('e1').set('transform', 'eigenfrequency');
model.sol('sol1').feature('e1').set('neigs', 50);
model.sol('sol1').feature('e1').set('shift', '1[Hz]');
model.sol('sol1').feature('e1').set('linpmethod', 'sol');
model.sol('sol1').feature('e1').set('linpsol', 'sol1');
model.sol('sol1').feature('e1').set('linpsoluse', 'sol2');
model.sol('sol1').feature('e1').set('solnum', 'auto');
model.sol('sol1').feature('e1').set('storelinpoint', true);
model.sol('sol1').feature('e1').feature('aDef').set('cachepattern', true);
model.sol('sol1').runAll;

model.result.evaluationGroup('stdEvgFrq').label('Eigenfrequencies (Study)');
model.result.evaluationGroup('stdEvgFrq').feature('gev1').set('expr', {'freq*2*pi' 'imag(freq)/abs(freq)' 'abs(freq)/imag(freq)/2'});
model.result.evaluationGroup('stdEvgFrq').feature('gev1').set('unit', {'rad/s' '1' '1'});
model.result.evaluationGroup('stdEvgFrq').feature('gev1').set('descr', {'Angular frequency' 'Damping ratio' 'Quality factor'});
model.result.evaluationGroup('stdEvgFrq').feature('gev1').set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
model.result('pg1').label('Mode Shape (solid)');
model.result('pg1').set('showlegends', false);
model.result('pg1').feature('surf1').set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
model.result('pg1').feature('surf1').set('colortable', 'AuroraBorealis');
model.result('pg1').feature('surf1').set('resolution', 'normal');

out = model;
